name: Android CI

on:
  workflow_dispatch:
    inputs:
      exoplayer_version:
        default: 2.11.x
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Show file content
      run: |
      
        echo "<settings>" > ~/.m2/settings1.xml
        echo "<profiles>" >> ~/.m2/settings1.xml
        echo "<profile>" >> ~/.m2/settings1.xml
        echo "<id>gpg</id>" >> ~/.m2/settings1.xml
        echo "<properties>" >> ~/.m2/settings1.xml
        echo "<gpg.executable>gpg</gpg.executable>" >> ~/.m2/settings1.xml
        echo "<gpg.passphrase>${{ secrets.TEST }}</gpg.passphrase>" >> ~/.m2/settings1.xml
        echo "</properties>" >> ~/.m2/settings1.xml
        echo "</profile>" >> ~/.m2/settings1.xml
        echo "</profiles>" >> ~/.m2/settings1.xml
        echo "<activeProfiles>" >> ~/.m2/settings1.xml
        echo "<activeProfile>gpg</activeProfile>" >> ~/.m2/settings1.xml
        echo "</activeProfiles>" >> ~/.m2/settings1.xml
        echo "<servers>" >> ~/.m2/settings1.xml
        echo "<server>" >> ~/.m2/settings1.xml
        echo "<id>github</id>" >> ~/.m2/settings1.xml
        echo "<username>${{ secrets.TEST }}</username>" >> ~/.m2/settings1.xml
        echo "<password>${{ secrets.TEST }}</password>" >> ~/.m2/settings1.xml
        echo "</server>" >> ~/.m2/settings1.xml
        echo "<server>" >> ~/.m2/settings1.xml
        echo "<id>ossrh</id>" >> ~/.m2/settings1.xml
        echo "<username>${{ secrets.TEST }}</username>" >> ~/.m2/settings1.xml
        echo "<password>${{ secrets.TEST }}</password>" >> ~/.m2/settings1.xml
        echo "</server>" >> ~/.m2/settings1.xml
        echo "</servers>" >> ~/.m2/settings1.xml
        echo "<localRepository>/tmp/mvn</localRepository>" >> ~/.m2/settings1.xml
        echo "</settings>" >> ~/.m2/settings1.xml

        ls -la ~/
        cat  ~/.m2/settings1.xml
        
    - name: Build dist
      env:
        VERSION: ${{ github.event.inputs.exoplayer_version }}
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        MAVEN_KEYID: ${{ secrets.MAVEN_KEYID }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        MAVEN_SECRING_PATH: ${{ secrets.MAVEN_SECRING_PATH }}
      run: ./dist.sh $VERSION
